### ISSUE TITLE
I'm facing a Bug with running your code in the terminal (I'm on MAC)

### ISSUE THREAD

**Issue by Nico-Yesu** [cetinsamet/music-genre-classification#1]
Here is what I get when I run the code:

(base) Nicos-MacBook-Pro:src nico$ python3 get_genre.py ../test.mp3

Traceback (most recent call last):
  File "get_genre.py", line 61, in <module>
    main(sys.argv[1:])
  File "get_genre.py", line 30, in main
    net.load_state_dict(torch.load(MODELPATH, map_location='cpu'))
  File "/Users/nico/opt/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 419, in load
    f = open(f, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '../utils/net.pt'

--------------------------------------------------
What does this mean and how can I fix this issue? Thank you in advance for your response.

**Comment by cetinsamet** [comment]
It's because the path of the network is defined incorrectly in config file. 
I think it is resolved now. 
Best.

**Comment by Nico-Yesu** [comment]
Thanks for reaching out! So I renamed the file to match the path and now the only thing thats going wrong now is when I run your program nothing happens in the terminal:

Here is a screen shot:


Is the output placed into another file? Or is it supposed to be in the terminal.

Best,
Nico

**Comment by cetinsamet** [comment]
@Nico-Yesu  Actually, I committed new changes to repository so it would be much safer and better if you can clone the repo again. 

Unfortunately, I cannot see any screenshot but there should be a printed output on terminal screen.

**Comment by Nico-Yesu** [comment]
This works now! Thank you very much, Closing the issue.
